AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  
Metrics/AbcSize:
  Enabled: false

Naming/MethodName:
  Enabled: false
